include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/gen/**"
    - "packages/**"
    - build/**
    - android/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Ilova public API emas — har widget uchun dartdoc shart emas.
    public_member_api_docs: false
